In [1]:
# --- packages --- #
import numpy  as np 
import pandas as pd
import os, sys, glob
pd.set_option("display.max_columns", None) # to show all columns when displaying dataframes

from magicctapipe.io import get_dl2_mean
from lstchain.reco.utils import get_effective_time
from astropy import units as u
from astropy.coordinates import SkyCoord
from magicctapipe.utils import calculate_off_coordinates

# select in order to process or not the data, or only 
# reading the already created dataframes
process = [False, # total stereo dataframe
           False, # magic-cta-pipe for stereo data
           False, # lstchain LST
           False, # magic-cta-pipe for lst
           False, # mars magic stereo
           False, # magic-cta-pipe for magic stereo
           False] # intersecting events between mars data and magic-cta-pipe data

# --- source we are going to analyse --- #
source_name = 'Crab'

# --- directories --- #
dir_stereo_reco   = '/fefs/aswg/workspace/juan.jimenez/data/datasets/'
dl2_dir           = '/fefs/aswg/workspace/juan.jimenez/data/dl2/stereo'
# ---- filenames ---- #
common_data_file  = '/fefs/aswg/workspace/juan.jimenez/stereo_analysis/config_files/common_data.txt'
name_stereo_3T    = 'stereo_data_3T'
name_stereo_total = 'stereo_data_total'
name_dl2_lst_2    = 'stereo_data_LST'
name_dl2_lst_1    = 'dl2_data_LST'
name_dl2_magic    = 'dl2_data_MAGIC'
name_stereo_magic = 'stereo_data_MAGIC'

# mask filename for dl2 LST data
mask_files   = '/fefs/aswg/workspace/abelardo.moralejo/jjimenez_master/Crab_LST1/DL2/dl2_*.h5'
# root directory for melibea data
root_melibea = '/fefs/aswg/workspace/juan.jimenez/data/dl2/melibea/melibeaCommonCrabNebula.h5'

# Total dataset of `dl2` with `magic-cta-pipe`

In [2]:
# --- finding the run id's we want to study --- #
if process[0] == True:
    
    print(f'Finding the runs contained in \'common_data.txt\' file')
    run_strings = np.loadtxt(common_data_file, dtype='str')
    run_id_LST  = [int(f.split('-')[0]) for f in run_strings] 
    
    # extracting dataframes
    all_files = os.listdir(dl2_dir)
    all_runs  = [int(f[-8:-3]) for f in all_files]
    
    # find the solicited runs at the directory
    run_files, run_ids = [], []
    for r in run_id_LST:  
        
        if r in all_runs:
            tmp_index = all_runs.index(r)       
            run_ids.append(r)
            run_files.append(os.path.join(dl2_dir, all_files[tmp_index]))      
            
    # sorting the runs
    run_files, run_ids = np.array(run_files), np.array(run_ids)
    run_files = run_files[run_ids.argsort()]
    run_ids.sort()
    print(f'Found {len(run_ids)} LST runs and converting it to dataframes')

    # --- converting to dataframe --- #
    # reading dataframes and putting all together into a unique dataframe
    df_total = [pd.read_hdf(f, key='/events/parameters') for f in run_files]
    df_total = pd.concat(df_total)

    # --- filtering only 3 telescopes events --- #
    print(f'\n3-Telescopes events filtering\nPassing from {len(df_total)} events')
    nevents_total = len(df_total)
    df_total.query('combo_type == 3', inplace=True)
    print(f'to {len(df_total)} events, {len(df_total) / nevents_total * 100:.2f}% conserved')

    # --- setting indexes --- #
    df_total.set_index(['obs_id', 'event_id', 'tel_id'], inplace=True)
    df_total.sort_index(inplace=True)

    # --- creating a unique identification --- #
    print(f'\nCreating a unique \'run.event\' identification label')
    # extracting indexes, runs and events
    indexdf = df_total.index.to_numpy()
    indexdf = np.array([np.array(_indexdf_) for _indexdf_ in indexdf]).T[:2]
    
    index_run_magic   = df_total['obs_id_magic'  ].to_numpy()
    index_event_magic = df_total['event_id_magic'].to_numpy()
    
    # creating the run.event labels
    universal_id = [f'{indexdf[0][i]}.{indexdf[1][i]}'             for i in range(len(indexdf[0]))]
    magic_id     = [f'{index_run_magic[i]}.{index_event_magic[i]}' for i in range(len(index_run_magic))]
    
    df_total['total_id'] = universal_id
    df_total['magic_id'] = magic_id  
    
    # --- create .h5 file --- #
    print('Creating .h5 files\n')
    df_total.to_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_total}.h5'), key='events')

# --- reading in the case it is already created --- #
df_total = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_total}.h5'))

# and printing an example of dataframe
print(f'Total dataframe for 3 telescopes data ({int(len(df_total) / 3)} events):')
display(df_total.head(5))

Total dataframe for 3 telescopes data (1597037 events):

                        obs_id_magic  event_id_magic  obs_id_lst  \
obs_id event_id tel_id
2923   2054766  1            5093174            2132      2923.0
                2            5093174            2132      2923.0
                3            5093174            2132      2923.0
       2054879  1            5093174            2134      2923.0
                2            5093174            2134      2923.0

                        event_id_lst    intensity         x         y  \
obs_id event_id tel_id
2923   2054766  1          2054766.0  1539.117331  0.159153 -0.199730
                2          2054766.0   682.101041  0.219247 -0.123636
                3          2054766.0   830.125000  0.211807 -0.165825
       2054879  1          2054879.0   222.561295 -0.455197  0.046522
                2          2054879.0   185.757812  0.322648  0.192534

                               r         phi    length  length_uncertainty  \
obs_id event_id tel_id
2923   2054766  1       0.255385  -51.450648  0.095864            0.003028
                2       0.251705  -29.419061  0.100258            0.002468
                3       0.268999  -38.057629  0.094508            0.003121
       2054879  1       0.457568  174.164535  0.041649            0.003202
                2       0.375727   30.825800  0.036762            0.001455

                           width  width_uncertainty        psi  skewness  \
obs_id event_id tel_id
2923   2054766  1       0.041476           0.001832  39.938156 -0.450708
                2       0.039357           0.001128  65.294646 -0.720628
                3       0.030039           0.000740  80.270400  0.379087
       2054879  1       0.032359           0.001995 -78.978052 -0.425175
                2       0.028710           0.001415  24.925432  0.411584

                        kurtosis     slope  intercept  intensity_width_1  \
obs_id event_id tel_id
2923   2054766  1       2.467139 -7.488149  19.800128                0.0
                2       2.653032  7.173953  15.740397                0.0
                3       4.620778 -5.738219  18.871566                0.0
       2054879  1       2.256291 -2.457408  15.740922                0.0
                2       2.163804  3.734823  12.596438                0.0

                        intensity_width_2  pixels_width_1  pixels_width_2  \
obs_id event_id tel_id
2923   2054766  1                0.000000             0.0        0.000000
                2                0.000000             0.0        0.000000
                3                0.000000             0.0        0.000000
       2054879  1                0.000000             0.0        0.000000
                2                0.022543             0.0        0.000962

                        n_pixels  n_islands  pointing_alt  pointing_az  \
obs_id event_id tel_id
2923   2054766  1             42          1      0.784340     1.508031
                2             61          1      0.784258     1.508029
                3             46          2      0.784235     1.508001
       2054879  1             10          1      0.784341     1.508032
                2             19          1      0.784258     1.508029

                           timestamp  time_diff  multiplicity  combo_type  \
obs_id event_id tel_id
2923   2054766  1       1.605743e+09   0.000020             3           3
                2       1.605743e+09   0.002003             3           3
                3       1.605743e+09   0.002003             3           3
       2054879  1       1.605743e+09   0.000029             3           3
                2       1.605743e+09   0.004651             3           3

                              alt  alt_uncert         az  az_uncert  \
obs_id event_id tel_id
2923   2054766  1       45.713880    0.185925  86.308094   0.185925
                2       45.713880    0.185925  86.308094   0.185925
                3       45.713880    0.185925  86.308094   0.185925
       2054879  1       44.084167    0.043847  86.058672   0.043847
                2       44.084167    0.043847  86.058672   0.043847

                           core_x     core_y      impact         h_max  \
obs_id event_id tel_id
2923   2054766  1       68.437147 -50.467934  117.100531  15205.132850
                2       68.437147 -50.467934   30.898989  15205.132850
                3       68.437147 -50.467934  101.768394  15205.132850
       2054879  1      -17.731262  75.937393    9.744626   3143.202157
                2      -17.731262  75.937393  110.243325   3143.202157

                        reco_energy  reco_energy_var  reco_disp  \
obs_id event_id tel_id
2923   2054766  1          1.160295         0.009623   0.818525
                2          0.966992         0.025346   0.597132
                3          1.013951         0.014466   0.709431
       2054879  1          0.349667         0.582411   0.734034
                2          0.219313         0.184645   1.042573

                        reco_disp_var   reco_alt    reco_az  disp_diff_sum  \
obs_id event_id tel_id
2923   2054766  1            0.033666  45.892510  86.571648       0.380246
                2            0.049796  45.873738  86.624261       0.380246
                3            0.023396  45.719292  86.656433       0.380246
       2054879  1            0.222867  44.145013  85.532415       2.757250
                2            0.287025  45.004017  86.638993       2.757250

                        disp_diff_mean  gammaness  gammaness_var  \
obs_id event_id tel_id
2923   2054766  1             0.126749   0.905000       0.085975
                2             0.126749   0.023333       0.022789
                3             0.126749   0.531095       0.249033
       2054879  1             0.919083   0.024167       0.023583
                2             0.919083   0.005000       0.004975

                            total_id      magic_id
obs_id event_id tel_id
2923   2054766  1       2923.2054766  5093174.2132
                2       2923.2054766  5093174.2132
                3       2923.2054766  5093174.2132
       2054879  1       2923.2054879  5093174.2134
                2       2923.2054879  5093174.2134

# Stereo 3T with `magic-cta-pipe`

In [3]:
# --- finding the run id's we want to study --- #
n_regions_off = 1

if process[1] == True:

    # --- calculating stereo events --- #
    print('\nReconstructing stereo events')
    df_3T_cta = get_dl2_mean(df_total, weight_type='variance')

    ######################################
    # -------- computing theta2 -------- #  
    
    print(f'\nComputing theta^2 values for the given data')
    time_diffs = np.diff(df_3T_cta['timestamp'])
    obs_time   = time_diffs[time_diffs < 1].sum() * u.s
    obs_time   = obs_time.to('h')
    print(f'Observation time: {obs_time:.1f}')     
    
    # extracting sky coordinates of the source we are studing
    on_coord = SkyCoord.from_name(source_name, frame='icrs')
    print(f'ON coordinate ({source_name}):\n{on_coord}')

    # converting the coordinated to degrees
    xlim = on_coord.ra.to_value('deg')  + np.array([2, -2])
    ylim = on_coord.dec.to_value('deg') + np.array([-2, 2])

    # now for the off sections
    print(f'\nNumber of OFF regions: {n_regions_off}')
    # loop over every observation ID
    obs_ids = np.unique(df_3T_cta.index.get_level_values('obs_id'))
    for obs_id in obs_ids:

        # filtering for only the events of a specific run
        df_events = df_3T_cta.query(f'obs_id == {obs_id}')

        # converting to gedrees
        event_coords = SkyCoord(u.Quantity(df_events['reco_ra' ], unit='deg'),
                                u.Quantity(df_events['reco_dec'], unit='deg'),
                                frame='icrs',)

        # pointing directions
        pnt_ra_mean  = df_events['pointing_ra' ].mean() * u.deg
        pnt_dec_mean = df_events['pointing_dec'].mean() * u.deg

        # calculate the angular distances from the ON region
        theta_on  = on_coord.separation(event_coords)
        theta2_on = theta_on.to_value('deg') ** 2

        df_3T_cta.loc[(obs_id, slice(None)), 'theta2_on'] = theta2_on
        df_3T_cta.loc[(obs_id, slice(None)), 'theta2_on'] = theta2_on

        # calculate the OFF coordinates
        off_coords = calculate_off_coordinates(pointing_ra  = pnt_ra_mean,
                                               pointing_dec = pnt_dec_mean,
                                               on_coord_ra  = on_coord.ra,
                                               on_coord_dec = on_coord.dec,
                                               n_regions    = n_regions_off,)

        # loop over every OFF coordinate
        for i_off, off_coord in off_coords.items():
            
            # calculate the angular distance from the OFF coordinate
            theta_off  = off_coord.separation(event_coords)
            theta2_off = theta_off.to_value('deg') ** 2

            df_3T_cta.loc[(obs_id, slice(None)), f'theta2_off'] = theta2_off
            
    # ---------------------------------- #
    ######################################
    
    # --- adding some more information --- #
    # df_1tel = df_total.query(f'tel_id == 1', inplace=False)
    # df_3T_cta[] = 
    
    # --- creating a unique identification --- #
    print(f'\nCreating a unique \'run.event\' identification label')
    # extracting indexes, runs and events
    indexdf = df_3T_cta.index.to_numpy()
    indexdf = np.array([np.array(_indexdf_) for _indexdf_ in indexdf]).T
    
    # creating the run.event labels
    universal_id = [f'{indexdf[0][i]}.{indexdf[1][i]}' for i in range(len(indexdf[0]))]    
    df_3T_cta['total_id'] = universal_id
    
    # --- create .h5 file --- #
    print('Creating .h5 files\n')
    df_3T_cta.to_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_3T}.h5'), key='events')

# --- reading in the case it is already created --- #
df_3T_cta = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_3T}.h5'))

# and printing an example of dataframe
print(f'Stereo reconstruction for 3-telescopes ({int(len(df_3T_cta))} events):')
display(df_3T_cta.head(5))

Stereo reconstruction for 3-telescopes (1597037 events):

                 combo_type  multiplicity     timestamp  pointing_alt  \
obs_id event_id
2923   2054766            3             3  1.605743e+09      0.784278
       2054879            3             3  1.605743e+09      0.784278
       2054932            3             3  1.605743e+09      0.784279
       2055078            3             3  1.605743e+09      0.784279
       2055274            3             3  1.605743e+09      0.784281

                 pointing_az  reco_energy   reco_alt    reco_az  gammaness  \
obs_id event_id
2923   2054766      1.508020     1.073560  45.808426  86.622282   0.229856
       2054879      1.508021     0.304828  44.365858  86.053244   0.005571
       2054932      1.508021     0.308370  43.797085  85.651368   0.575596
       2055078      1.508021     6.024152  44.133521  89.574563   0.010758
       2055274      1.508022     2.305442  43.991970  87.230756   0.217573

                 pointing_ra  pointing_dec    reco_ra   reco_dec  theta2_on  \
obs_id event_id
2923   2054766     83.966939     22.246320  83.020361  22.381911   0.457941
       2054879     83.966939     22.246321  84.636853  22.297141   0.944449
       2054932     83.966939     22.246322  85.319784  22.385995   2.577053
       2055078     83.966940     22.246323  83.945537  19.847722   4.774763
       2055274     83.966940     22.246324  84.715779  21.376468   1.417173

                 theta2_off      total_id
obs_id event_id
2923   2054766     1.416898  2923.2054766
       2054879     0.127986  2923.2054879
       2054932     0.890579  2923.2054932
       2055078     7.036542  2923.2055078
       2055274     1.362165  2923.2055274

# LST-1 `dl2` data with `lstchain`

In [4]:
# --- reading dataset --- #
dataset = glob.glob(mask_files)
dataset.sort()
tablename = '/dl2/event/telescope/parameters/LST_LSTCam'

# --- calibration parameters --- #
nominal_focal = 28       * u.m
focal         = 29.30565 * u.m
aberration_correction = focal / nominal_focal

tmp_df = pd.read_hdf(dataset[0], tablename)
print(f'Full dataframe for LST analysis example:')
display(tmp_df.head(5))
del tmp_df

# --- column data to extract --- #
columns = ['obs_id', 'event_id', 'intensity', 'x', 'y', 'r', 'time_gradient', 'intercept',
           'alt_tel', 'az_tel', 'dragon_time', 'delta_t', 
           'reco_energy', 'reco_alt', 'reco_az', 'gammaness', 
           'reco_src_x', 'reco_src_y', 'reco_disp_norm']

if process[2] == True:
    
    # extracting lst runs form stereo file
    lst_runs = np.unique(df_total['obs_id_lst'].to_numpy())[:-1] # avoiding last one because it is a None

    # --- iterating over all files --- #
    print(f'\nIterating over all filenames {len(lst_runs)} runs\n')
    table, table2, t_eff, t_elapsed = [], [], 0, 0
    for file in dataset:
        
        # only appending the data if LST run is contained in stereo LST runs
        if int(file[-8: -3]) in lst_runs:
            
            print(f'Reading {file}')
            # temporal table with only the requested columns
            tb = pd.read_hdf(file, tablename)[columns]
            # getting the times of the events
            lt, et = get_effective_time(tb)
            t_eff     += lt
            t_elapsed += et
            
            # appending to main dataframes
            table.append(tb)
            table2.append(pd.read_hdf(file, 'source_position'))
            
    # concatenating the dataframes
    table  = pd.concat(table)
    table2 = pd.concat(table2)

    ###########################################
    # ---------- computing theta2 ----------- #  
    # --- adding the source_position info --- #
    print(f'\nAdding the source position info and theta data')
    for var in table2:
        table[var] = table2[var]
        
    table['src_x'] *= aberration_correction
    table['src_y'] *= aberration_correction
    
    dx = np.rad2deg((table['reco_src_x'] - table['src_x']) / focal.to_value(u.m))
    dy = np.rad2deg((table['reco_src_y'] - table['src_y']) / focal.to_value(u.m))
    
    # creating the theta 2 data for the on and off source
    table['theta2_on']  = (dx ** 2 + dy ** 2).astype('float32')
    
    # now the theta2 angle relative to the off position (opposite to the source position with respect to the 
    # center of the camera):
    dx = np.rad2deg((table['reco_src_x'] + table['src_x']) / focal.to_value(u.m))
    dy = np.rad2deg((table['reco_src_y'] + table['src_y']) / focal.to_value(u.m))
    table['theta2_off'] = (dx ** 2 + dy ** 2).astype('float32')
    
    # -------------------------------------- #
    ##########################################

    # --- now filter only the events that we have in stereo 3T data --- #
    print('\nFiltering only stereo coincident events:')
    df_lst_lst = []
    for r in lst_runs:
        print(f'Matching events from Run {int(r)}')
        
        # temporal table
        tb = table.query(f'obs_id == {r}', inplace=False)
        
        # reduced dataset for the run
        tmp_run_stereo = df_total.query(f'obs_id_lst == {r}', inplace=False)
        # getting the eventlist for that run in the stereo data
        lst_events = list(np.unique(tmp_run_stereo['event_id_lst'].to_numpy()))
        
        # filtering coincident events
        tb = tb.query(f'event_id in @lst_events', inplace=False)
        df_lst_lst.append(tb)
        
    # concatenating
    df_lst_lst = pd.concat(df_lst_lst)

    # --- creating a unique identification --- #
    index_run    = df_lst_lst['obs_id'].to_numpy()
    index_event  = df_lst_lst['event_id'].to_numpy()
    universal_id = [f'{index_run[i]}.{index_event[i]}' for i in range(len(index_run))]
    df_lst_lst['total_id'] = universal_id

    # --- create .h5 file --- #
    print('\nCreating .h5 files')
    df_lst_lst.to_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_lst_1}.h5'), key='events')

# --- reading in the case it is already created --- #
df_lst_lst = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_lst_1}.h5'))

# and printing an example of both dataframes
print(f'Total dataframe for LST events processed with lstchain ({int(len(df_lst_lst))} events):')
display(df_lst_lst.head(5))

Full dataframe for LST analysis example:

,obs_id,event_id,intensity,log_intensity,x,y,r,phi,length,length_uncertainty,width,width_uncertainty,psi,skewness,kurtosis,time_gradient,intercept,leakage_intensity_width_1,leakage_intensity_width_2,leakage_pixels_width_1,leakage_pixels_width_2,n_pixels,concentration_cog,concentration_core,concentration_pixel,n_islands,alt_tel,az_tel,calibration_id,dragon_time,ucts_time,tib_time,ucts_jump,mc_type,wl,tel_id,tel_pos_x,tel_pos_y,tel_pos_z,trigger_type,ucts_trigger_type,trigger_time,event_type,delta_t,log_reco_energy,reco_energy,reco_disp_norm,reco_disp_sign,reco_disp_dx,reco_disp_dy,reco_src_x,reco_src_y,signed_time_gradient,signed_skewness,reco_alt,reco_az,reco_type,gammaness
0,2923,1,4750.837479,3.676770,0.020278,-0.020556,0.028875,-0.792216,1.152664,0.007966,1.136915,0.008164,-0.705672,0.077260,1.907330,5.999886,18.367545,0.048739,0.134111,0.014555,0.042049,585,0.000000,0.252337,0.005150,47,0.773309,1.502663,0,1.605742e+09,0,0,False,-9999,0.986337,1,50.0,50.0,16.0,1,1,1.605742e+09,32,0.000000,0.354637,2.262752,0.346116,-1.0,-0.263455,0.224472,-0.243177,0.203916,5.999886,0.077260,0.764598,1.512755,101,0.012927
1,2923,4,189.873543,2.278464,-0.881320,0.091974,0.886106,3.037609,0.080447,0.003944,0.076714,0.004265,-0.518965,-0.608622,2.825843,0.653417,16.973236,0.000000,0.000000,0.000000,0.000000,11,0.637727,0.396991,0.219657,1,0.773309,1.502663,0,1.605742e+09,0,0,False,-9999,0.953599,1,50.0,50.0,16.0,1,1,1.605742e+09,32,0.000240,-0.857237,0.138919,0.122087,1.0,0.106012,-0.060553,-0.775308,0.031422,-0.653417,0.608622,0.745618,1.504190,101,0.046854
2,2923,8,83.977066,1.924161,0.197419,-1.022370,1.041256,-1.380044,0.070698,0.003570,0.030269,0.004525,-1.358085,0.112017,1.856350,-5.128817,13.302960,0.239729,0.643990,0.001617,0.002156,5,0.760271,0.404261,0.404261,1,0.773309,1.502663,0,1.605742e+09,0,0,False,-9999,0.428143,1,50.0,50.0,16.0,1,1,1.605742e+09,32,0.000028,-1.125323,0.074934,0.264438,1.0,0.055826,-0.258478,0.253245,-1.280848,5.128817,-0.112017,0.781323,1.438213,101,0.092983
3,2923,9,271.288065,2.433431,-0.288294,-0.319626,0.430435,-2.304699,0.085006,0.003115,0.076062,0.002965,0.049170,-0.178970,2.456776,-10.681323,13.729140,0.000000,0.000000,0.000000,0.000000,15,0.581858,0.196471,0.202958,1,0.773309,1.502663,0,1.605742e+09,0,0,False,-9999,0.894779,1,50.0,50.0,16.0,1,1,1.605742e+09,32,0.000218,-0.705513,0.197009,0.113204,-1.0,-0.113067,-0.005564,-0.401361,-0.325190,-10.681323,-0.178970,0.758909,1.486658,0,0.635426
4,2923,10,180.602312,2.256723,0.676302,-0.796871,1.045174,-0.867060,0.094225,0.004693,0.070820,0.004625,-1.561171,0.578821,2.792075,-13.337788,15.154821,0.048954,0.419290,0.000539,0.003235,10,0.367813,0.292555,0.185141,1,0.773309,1.502663,0,1.605742e+09,0,0,False,-9999,0.751612,1,50.0,50.0,16.0,1,1,1.605742e+09,32,0.000057,-0.875975,0.133053,0.137471,-1.0,-0.001323,0.137464,0.674979,-0.659407,-13.337788,0.578821,0.797138,1.468967,0,0.557790

Total dataframe for LST events processed with lstchain (1597037 events):

,obs_id,event_id,intensity,x,y,r,time_gradient,intercept,alt_tel,az_tel,dragon_time,delta_t,reco_energy,reco_alt,reco_az,gammaness,reco_src_x,reco_src_y,reco_disp_norm,src_x,src_y,brightest_pixel,theta2_on,theta2_off,total_id
641447,2923,2054766,1539.117331,0.159153,-0.199730,0.255385,-7.488149,19.800128,0.784340,1.508031,1.605743e+09,0.000020,1.296785,0.802239,1.512487,0.849113,0.501298,0.086735,0.446235,0.109220,0.162819,199.895172,0.609734,1.662808,2923.2054766
641482,2923,2054879,222.561295,-0.455197,0.046522,0.457568,-2.457408,15.740922,0.784341,1.508032,1.605743e+09,0.000029,0.147946,0.769320,1.501430,0.050762,-0.420268,-0.132808,0.182700,0.109220,0.162821,43.858879,1.405720,0.373269,2923.2054879
641495,2923,2054932,493.258595,-0.599963,-0.179310,0.626185,10.961353,15.071617,0.784341,1.508032,1.605743e+09,0.000047,0.558524,0.766855,1.489840,0.201653,-0.487265,-0.366841,0.218789,0.109219,0.162821,54.278393,2.432366,0.705407,2923.2054932
641535,2923,2055078,5716.545122,-0.133117,0.249002,0.282351,12.083996,26.947308,0.784342,1.508032,1.605743e+09,0.000082,5.329910,0.775219,1.554315,0.006266,-0.240307,0.925506,0.684944,0.109219,0.162823,159.810211,2.690452,4.593233,2923.2055078
641595,2923,2055274,1982.416317,0.194891,0.360309,0.409640,14.399923,16.464350,0.784343,1.508032,1.605743e+09,0.000009,3.378833,0.769079,1.519712,0.006773,-0.426417,0.235006,0.633818,0.109217,0.162825,82.557724,1.116594,0.989577,2923.2055274

# LST-1 `dl2` data with `magic-cta-pipe`

In [5]:
# --- restricting the total dataframe to lst --- #
n_regions_off = 1

if process[3] == True:
    
    # --- copying the total dataframe --- #
    print(f'Copying and filtering only-LST data from total dataframe')
    df_lst_cta = df_total.copy()

    # --- filtering only LST telescope --- #
    df_lst_cta.query('tel_id == 1', inplace=True)

    # --- calculating stereo events --- #
    print('\nReconstructing stereo events')
    df_lst_cta = get_dl2_mean(df_lst_cta, weight_type='simple')

    ######################################
    # -------- computing theta2 -------- #  
    
    print(f'\nComputing theta^2 values for the given data')
    time_diffs = np.diff(df_lst_cta['timestamp'])
    obs_time   = time_diffs[time_diffs < 1].sum() * u.s
    obs_time   = obs_time.to('h')
    print(f'Observation time: {obs_time:.1f}')     
    
    # extracting sky coordinates of the source we are studing
    on_coord = SkyCoord.from_name(source_name, frame='icrs')
    print(f'ON coordinate ({source_name}):\n{on_coord}')

    # converting the coordinated to degrees
    xlim = on_coord.ra.to_value('deg')  + np.array([2, -2])
    ylim = on_coord.dec.to_value('deg') + np.array([-2, 2])

    # now for the off sections
    print(f'\nNumber of OFF regions: {n_regions_off}')
    # loop over every observation ID
    obs_ids = np.unique(df_lst_cta.index.get_level_values('obs_id'))
    for obs_id in obs_ids:

        # filtering for only the events of a specific run
        df_events = df_lst_cta.query(f'obs_id == {obs_id}')

        # converting to gedrees
        event_coords = SkyCoord(u.Quantity(df_events['reco_ra'],  unit='deg'),
                                u.Quantity(df_events['reco_dec'], unit='deg'),
                                frame='icrs',)

        # pointing directions
        pnt_ra_mean  = df_events['pointing_ra'].mean()  * u.deg
        pnt_dec_mean = df_events['pointing_dec'].mean() * u.deg

        # calculate the angular distances from the ON region
        theta_on  = on_coord.separation(event_coords)
        theta2_on = theta_on.to_value('deg') ** 2

        df_lst_cta.loc[(obs_id, slice(None)), 'theta2_on'] = theta2_on
        df_lst_cta.loc[(obs_id, slice(None)), 'theta2_on'] = theta2_on

        # calculate the OFF coordinates
        off_coords = calculate_off_coordinates(pointing_ra  = pnt_ra_mean,
                                               pointing_dec = pnt_dec_mean,
                                               on_coord_ra  = on_coord.ra,
                                               on_coord_dec = on_coord.dec,
                                               n_regions    = n_regions_off,)

        # loop over every OFF coordinate
        for i_off, off_coord in off_coords.items():
            
            # calculate the angular distance from the OFF coordinate
            theta_off  = off_coord.separation(event_coords)
            theta2_off = theta_off.to_value('deg') ** 2

            df_lst_cta.loc[(obs_id, slice(None)), f'theta2_off'] = theta2_off
            
    # ---------------------------------- #
    ######################################    
    
    # --- creating a unique identification --- #
    print(f'\nCreating a unique \'run.event\' identification label')
    # extracting indexes, runs and events
    indexdf = df_lst_cta.index.to_numpy()
    indexdf = np.array([np.array(_indexdf_) for _indexdf_ in indexdf]).T
    
    # creating the run.event labels
    universal_id = [f'{indexdf[0][i]}.{indexdf[1][i]}' for i in range(len(indexdf[0]))]    
    df_lst_cta['total_id'] = universal_id
    
    
    # --- create .h5 file --- #
    print('Creating .h5 files')
    df_lst_cta.to_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_lst_2}.h5'), key='events')
    
# --- reading in the case it is already created --- #
df_lst_cta = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_lst_2}.h5'))

# and printing an example of both dataframes
print(f'Total dataframe for LST processed with magic-cta-pipe ({int(len(df_lst_cta))} events):')
display(df_lst_cta.head(5))

Total dataframe for LST processed with magic-cta-pipe (1597037 events):

                 combo_type  multiplicity     timestamp  pointing_alt  \
obs_id event_id
2923   2054766            3             3  1.605743e+09      0.784340
       2054879            3             3  1.605743e+09      0.784341
       2054932            3             3  1.605743e+09      0.784341
       2055078            3             3  1.605743e+09      0.784342
       2055274            3             3  1.605743e+09      0.784343

                 pointing_az  reco_energy   reco_alt    reco_az  gammaness  \
obs_id event_id
2923   2054766      1.508031     1.160295  45.892510  86.571648   0.905000
       2054879      1.508032     0.349667  44.145013  85.532415   0.024167
       2054932      1.508032     0.324521  43.923343  85.395259   0.259000
       2055078      1.508032     4.532147  44.364517  89.432862   0.005000
       2055274      1.508032     2.678414  43.922713  87.031510   0.000000

                 pointing_ra  pointing_dec    reco_ra   reco_dec  theta2_on  \
obs_id event_id
2923   2054766     83.963121     22.247061  82.946402  22.442243   0.588298
       2054879     83.963121     22.247064  84.993118  22.579120   1.903065
       2054932     83.963121     22.247065  85.254798  22.601497   2.596364
       2055078     83.963120     22.247069  83.754956  20.025401   3.964636
       2055274     83.963119     22.247074  84.837807  21.488128   1.527392

                 theta2_off      total_id
obs_id event_id
2923   2054766     1.560440  2923.2054766
       2054879     0.422463  2923.2054879
       2054932     0.796261  2923.2054932
       2055078     6.286444  2923.2055078
       2055274     1.237185  2923.2055274

# MAGIC stereo `dl2` with `MARS`

In [6]:
# --- analysing mars --- #
n_regions_off = 1

if process[4] == True:
    
    # --- reading the magic run ids that we have in stereo data --- #
    magic_runs = np.unique(df_total['obs_id_magic'].to_numpy())

    # --- reading dataframe --- #
    melibea_df = pd.read_hdf(root_melibea)

    # --- iterating over magic run ids and coincident events --- #
    print('\nFiltering only stereo coincident events:')
    df_magic_mars = []
    for r in magic_runs:
        print(f'Matching events from Run {int(r)}')

        # dataframe for a specific magic run
        tb = melibea_df.query(f'obs_id == {r}', inplace=False)

        # stereo dataframe for the specific magic run
        tmp_run_stereo = df_total.query(f'obs_id_magic == {r}', inplace=False)
        # extracting the magic event ids
        magic_events = list(np.unique(tmp_run_stereo['event_id_magic'].to_numpy()))

        # matching coincident events
        tb = tb.query(f'event_id in @magic_events', inplace=False)
        
        print(f'Found {len(tb)} events, {len(tb)/len(magic_events)*100:.2f}% from all stereo events')
        df_magic_mars.append(tb)

    # concatenating dataframes for each run
    df_magic_mars = pd.concat(df_magic_mars)
    
    # --- creating a unique identification --- #
    print(f'\nCreating a unique identification run.event in terms of the stereo event notation (not magic)')
    indexdf = df_magic_mars.index.to_numpy()
    indexdf = np.array([np.array(_indexdf_) for _indexdf_ in indexdf]).T[:2]
    # creating the run.event labels
    magic_id = [f'{indexdf[0][i]}.{indexdf[1][i]}' for i in range(len(indexdf[0]))]

    tmp_df = df_total.query(f'tel_id == {1}', inplace=False)
    ids_total_total = tmp_df['total_id'].to_numpy()
    ids_total_magic = tmp_df['magic_id'].to_numpy()

    # indexes_mars = np.searchsorted(ids_total_magic, magic_id)
    sort_idx = ids_total_magic.argsort()
    indexes_mars = sort_idx[np.searchsorted(ids_total_magic, magic_id, sorter=sort_idx)]
    
    df_magic_mars['total_id'] = ids_total_total[indexes_mars]
    

    ######################################
    # -------- computing theta2 -------- #  
    
    print(f'\nComputing theta^2 values for the given data')
    time_diffs = np.diff(df_magic_mars['timestamp'])
    obs_time   = time_diffs[time_diffs < 1].sum() * u.s
    obs_time   = obs_time.to('h')
    print(f'Observation time: {obs_time:.1f}')     
    
    # extracting sky coordinates of the source we are studing
    on_coord = SkyCoord.from_name(source_name, frame='icrs')
    print(f'ON coordinate ({source_name}):\n{on_coord}')

    # converting the coordinated to degrees
    xlim = on_coord.ra.to_value('deg')  + np.array([2, -2])
    ylim = on_coord.dec.to_value('deg') + np.array([-2, 2])

    # now for the off sections
    print(f'\nNumber of OFF regions: {n_regions_off}')
    # loop over every observation ID
    obs_ids = np.unique(df_magic_mars.index.get_level_values('obs_id'))
    for obs_id in obs_ids:

        # filtering for only the events of a specific run
        df_events = df_magic_mars.query(f'obs_id == {obs_id}')

        # converting to gedrees
        event_coords = SkyCoord(u.Quantity(df_events['reco_ra'],  unit='deg'),
                                u.Quantity(df_events['reco_dec'], unit='deg'),
                                frame='icrs',)

        # pointing directions
        pnt_ra_mean  = df_events['pointing_ra'].mean()  * u.deg
        pnt_dec_mean = df_events['pointing_dec'].mean() * u.deg

        # calculate the angular distances from the ON region
        theta_on  = on_coord.separation(event_coords)
        theta2_on = theta_on.to_value('deg') ** 2

        df_magic_mars.loc[(obs_id, slice(None)), 'theta2_on'] = theta2_on
        df_magic_mars.loc[(obs_id, slice(None)), 'theta2_on'] = theta2_on

        # calculate the OFF coordinates
        off_coords = calculate_off_coordinates(pointing_ra  = pnt_ra_mean,
                                               pointing_dec = pnt_dec_mean,
                                               on_coord_ra  = on_coord.ra,
                                               on_coord_dec = on_coord.dec,
                                               n_regions    = n_regions_off,)

        # loop over every OFF coordinate
        for i_off, off_coord in off_coords.items():
            
            # calculate the angular distance from the OFF coordinate
            theta_off  = off_coord.separation(event_coords)
            theta2_off = theta_off.to_value('deg') ** 2

            df_magic_mars.loc[(obs_id, slice(None)), f'theta2_off'] = theta2_off
            
    # ---------------------------------- #
    ###################################### 
    
    # create .h5 file
    print('\nCreating .h5 files')
    df_magic_mars.to_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_magic}.h5'), key='events')

# --- reading in the case it is already created --- #
df_magic_mars = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_magic}.h5'))

# and printing an example of both dataframes
print(f'Total dataframe for MAGIC events processed with MARS ({int(len(df_magic_mars))} events):')
display(df_magic_mars.head(5))

Total dataframe for MAGIC events processed with MARS (1597037 events):

                  intensity_M1  intensity_M2  src_pos_M1_X  src_pos_M1_Y  \
obs_id  event_id
5093174 2132        682.093750    830.125000    -95.093643    -67.696632
        2134        185.757812     60.031250    -95.094864    -67.695946
        2136        210.335938    165.843750    -95.095299    -67.695694
        2140       1205.257812   1114.429688    -95.096870    -67.694801
        2141         89.109375    321.953125    -95.099022    -67.693573

                  src_pos_M2_X  src_pos_M2_Y     imp_par_1  imp_par_1_Az  \
obs_id  event_id
5093174 2132        -95.007812    -69.127335     -1.000000           NaN
        2134        -95.007668    -69.127419     -1.000000           NaN
        2136        -95.007614    -69.127449  10347.416992   -135.922577
        2140        -95.007416    -69.127563  33543.277344    -39.197220
        2141        -95.007156    -69.127724  37166.769531    -96.054169

                     imp_par_2  imp_par_2_Az   st_dirX   st_dirY  reco_energy  \
obs_id  event_id
5093174 2132         -1.000000           NaN       NaN       NaN    -0.001000
        2134         -1.000000           NaN       NaN       NaN    -0.001000
        2136       4091.868408    -99.179375  0.462942  1.156278     0.277724
        2140      37507.761719    -28.356291 -1.925715  0.639971     8.409363
        2141      33981.015625    -84.813004 -0.776421  0.846694     1.542577

                  gammaness   reco_dec    reco_ra      h_max   slope_1  \
obs_id  event_id
5093174 2132       0.081321        NaN        NaN      -1.00  0.431198
        2134       0.000000        NaN        NaN      -1.00  1.135765
        2136       0.411683  22.298716  84.311796  891360.75  0.714785
        2140       0.000000  20.215153  84.403027  968357.00 -0.567660
        2141       0.251661  21.232567  84.362278  979809.25  1.497397

                   slope_2  pointing_ra  pointing_dec     timestamp   delta_t  \
obs_id  event_id
5093174 2132      0.169814    84.401111     22.243889  1.737312e+09  0.002003
        2134     -1.296749    84.401111     22.243889  1.737705e+09  0.004651
        2136     -1.347897    84.401111     22.243889  1.737845e+09  0.002138
        2140     -0.512080    84.401111     22.243889  1.738355e+09  0.003429
        2141     -1.392613    84.401111     22.243889  1.739049e+09  0.008976

                      total_id  theta2_on  theta2_off
obs_id  event_id
5093174 2132      2923.2054766        NaN         NaN
        2134      2923.2054879        NaN         NaN
        2136      2923.2054932   0.476342    0.660850
        2140      2923.2055078   3.748868    5.614933
        2141      2923.2055274   1.068782    2.104545

# MAGIC stereo `dl2` with `magic-cta-pipe`

In [7]:
# --- restricting the total datframe to magic only --- # 
n_regions_off = 1

if process[5] == True:
    
    # --- copying the total dataframe --- #
    print(f'Copying and filtering only-LST data from total dataframe')
    df_magic_cta = df_total.copy()

    # --- filtering only MAGIC telescopes --- #
    df_magic_cta.query('tel_id == 2 or tel_id == 3', inplace=True)

    # --- calculating stereo events --- #
    print('\nReconstructing stereo events only for the data of M1 and M2')
    df_magic_cta = get_dl2_mean(df_magic_cta, weight_type='variance')

    ######################################
    # -------- computing theta2 -------- #  
    
    print(f'\nComputing theta^2 values for the given data')
    time_diffs = np.diff(df_magic_cta['timestamp'])
    obs_time   = time_diffs[time_diffs < 1].sum() * u.s
    obs_time   = obs_time.to('h')
    print(f'Observation time: {obs_time:.1f}')     
    
    # extracting sky coordinates of the source we are studing
    on_coord = SkyCoord.from_name(source_name, frame='icrs')
    print(f'ON coordinate ({source_name}):\n{on_coord}')

    # converting the coordinated to degrees
    xlim = on_coord.ra.to_value('deg')  + np.array([2, -2])
    ylim = on_coord.dec.to_value('deg') + np.array([-2, 2])

    # now for the off sections
    print(f'\nNumber of OFF regions: {n_regions_off}')
    # loop over every observation ID
    obs_ids = np.unique(df_magic_cta.index.get_level_values('obs_id'))
    for obs_id in obs_ids:

        # filtering for only the events of a specific run
        df_events = df_magic_cta.query(f'obs_id == {obs_id}')

        # converting to gedrees
        event_coords = SkyCoord(
            u.Quantity(df_events['reco_ra'],  unit='deg'),
            u.Quantity(df_events['reco_dec'], unit='deg'),
            frame='icrs',)

        # pointing directions
        pnt_ra_mean  = df_events['pointing_ra'].mean()  * u.deg
        pnt_dec_mean = df_events['pointing_dec'].mean() * u.deg

        # calculate the angular distances from the ON region
        theta_on  = on_coord.separation(event_coords)
        theta2_on = theta_on.to_value('deg') ** 2

        df_magic_cta.loc[(obs_id, slice(None)), 'theta2_on'] = theta2_on
        df_magic_cta.loc[(obs_id, slice(None)), 'theta2_on'] = theta2_on

        # calculate the OFF coordinates
        off_coords = calculate_off_coordinates(pointing_ra  = pnt_ra_mean,
                                               pointing_dec = pnt_dec_mean,
                                               on_coord_ra  = on_coord.ra,
                                               on_coord_dec = on_coord.dec,
                                               n_regions    = n_regions_off,)

        # loop over every OFF coordinate
        for i_off, off_coord in off_coords.items():

            # calculate the angular distance from the OFF coordinate
            theta_off  = off_coord.separation(event_coords)
            theta2_off = theta_off.to_value('deg') ** 2

            df_magic_cta.loc[(obs_id, slice(None)), f'theta2_off'] = theta2_off
            
    # ---------------------------------- #
    ######################################  
    
    # --- creating a unique identification --- #
    print(f'\nCreating a unique \'run.event\' identification label')
    # extracting indexes, runs and events
    indexdf = df_magic_cta.index.to_numpy()
    indexdf = np.array([np.array(_indexdf_) for _indexdf_ in indexdf]).T
    
    # creating the run.event labels
    universal_id = [f'{indexdf[0][i]}.{indexdf[1][i]}' for i in range(len(indexdf[0]))]    
    df_magic_cta['total_id'] = universal_id
    
    
    # --- create .h5 file --- #
    print('\nCreating .h5 files')
    df_magic_cta.to_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_magic}.h5'), key='events')

# --- reading in the case it is already created --- #
df_magic_cta = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_magic}.h5'))

# and printing an example of both dataframes
print(f'Total dataframe for MAGIC events processed with magic-cta-pipe ({int(len(df_magic_cta))} events):')
display(df_magic_cta.head(5))

Total dataframe for MAGIC events processed with magic-cta-pipe (1597037 events):

                 combo_type  multiplicity     timestamp  pointing_alt  \
obs_id event_id
2923   2054766            3             3  1.605743e+09      0.784247
       2054879            3             3  1.605743e+09      0.784247
       2054932            3             3  1.605743e+09      0.784247
       2055078            3             3  1.605743e+09      0.784248
       2055274            3             3  1.605743e+09      0.784249

                 pointing_az  reco_energy   reco_alt    reco_az  gammaness  \
obs_id event_id
2923   2054766      1.508015     0.996630  45.768662  86.646169   0.065903
       2054879      1.508015     0.296239  44.516516  86.414089   0.004001
       2054932      1.508015     0.303546  43.737947  85.770560   0.733074
       2055078      1.508016     9.079893  44.005319  89.652684   0.024489
       2055274      1.508016     2.165051  44.097895  87.538358   0.868484

                 pointing_ra  pointing_dec    reco_ra   reco_dec  theta2_on  \
obs_id event_id
2923   2054766     83.968847     22.245950  83.055307  22.353374   0.402099
       2054879     83.968848     22.245950  84.392417  22.102560   0.502953
       2054932     83.968848     22.245950  85.350054  22.285380   2.602299
       2055078     83.968850     22.245949  84.051062  19.749081   5.279012
       2055274     83.968851     22.245949  84.528308  21.204422   1.346666

                 theta2_off      total_id
obs_id event_id
2923   2054766     1.354486  2923.2054766
       2054879     0.147417  2923.2054879
       2054932     0.967444  2923.2054932
       2055078     7.505535  2923.2055078
       2055274     1.664926  2923.2055274

## Filtering only coincident events between all

In [8]:
if process[6] == True:
    print(f'Finding total ids for all events in each case and reducing it to the total intersection...')
    ids_t_mars = df_magic_mars['total_id'].to_numpy()

    # calculating the events id intersection
    common_melibea_id = df_3T_cta.query(f'total_id in @ids_t_mars', inplace=False)['total_id'].to_numpy()

    print('Filtering the events\n')
    df_total.query(     f'total_id in @common_melibea_id', inplace=True)
    df_3T_cta.query(    f'total_id in @common_melibea_id', inplace=True)
    df_lst_cta.query(   f'total_id in @common_melibea_id', inplace=True)
    df_lst_lst.query(   f'total_id in @common_melibea_id', inplace=True)
    df_total.query(     f'total_id in @common_melibea_id', inplace=True)
    df_magic_cta.query( f'total_id in @common_melibea_id', inplace=True)
    df_magic_mars.query(f'total_id in @common_melibea_id', inplace=True)

    # --- overwritting again the dataframes --- #
    print('Creating .h5 files\n')
    df_total.to_hdf(     os.path.join(dir_stereo_reco, f'{name_stereo_total}.h5'), key='events')
    df_3T_cta.to_hdf(    os.path.join(dir_stereo_reco, f'{name_stereo_3T}.h5'),    key='events')
    df_lst_lst.to_hdf(   os.path.join(dir_stereo_reco, f'{name_dl2_lst_1}.h5'),    key='events')
    df_lst_cta.to_hdf(   os.path.join(dir_stereo_reco, f'{name_dl2_lst_2}.h5'),    key='events')
    df_magic_mars.to_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_magic}.h5'),    key='events')
    df_magic_cta.to_hdf( os.path.join(dir_stereo_reco, f'{name_stereo_magic}.h5'), key='events')

### Printing the dataframes

In [9]:
print(f'Total 3T dataframe ({int(len(df_total) / 3)} events):')
display(df_total.head(5))
print(f'3T stereo with magic-cta-pipe ({int(len(df_3T_cta))} events):')
display(df_3T_cta.head(5))
print(f'LST with magic-cta-pipe ({int(len(df_lst_cta))} events):')
display(df_lst_cta.head(5))
print(f'MAGIC with magic-cta-pipe ({int(len(df_magic_cta))} events):')
display(df_magic_cta.head(5))
print(f'LST with lstchain ({int(len(df_lst_lst))} events):')
display(df_lst_lst.head(5))
print(f'MAGIC with mars ({int(len(df_magic_mars))} events):')
display(df_magic_mars.head(5))

Total 3T dataframe (1597037 events):

                        obs_id_magic  event_id_magic  obs_id_lst  \
obs_id event_id tel_id
2923   2054766  1            5093174            2132      2923.0
                2            5093174            2132      2923.0
                3            5093174            2132      2923.0
       2054879  1            5093174            2134      2923.0
                2            5093174            2134      2923.0

                        event_id_lst    intensity         x         y  \
obs_id event_id tel_id
2923   2054766  1          2054766.0  1539.117331  0.159153 -0.199730
                2          2054766.0   682.101041  0.219247 -0.123636
                3          2054766.0   830.125000  0.211807 -0.165825
       2054879  1          2054879.0   222.561295 -0.455197  0.046522
                2          2054879.0   185.757812  0.322648  0.192534

                               r         phi    length  length_uncertainty  \
obs_id event_id tel_id
2923   2054766  1       0.255385  -51.450648  0.095864            0.003028
                2       0.251705  -29.419061  0.100258            0.002468
                3       0.268999  -38.057629  0.094508            0.003121
       2054879  1       0.457568  174.164535  0.041649            0.003202
                2       0.375727   30.825800  0.036762            0.001455

                           width  width_uncertainty        psi  skewness  \
obs_id event_id tel_id
2923   2054766  1       0.041476           0.001832  39.938156 -0.450708
                2       0.039357           0.001128  65.294646 -0.720628
                3       0.030039           0.000740  80.270400  0.379087
       2054879  1       0.032359           0.001995 -78.978052 -0.425175
                2       0.028710           0.001415  24.925432  0.411584

                        kurtosis     slope  intercept  intensity_width_1  \
obs_id event_id tel_id
2923   2054766  1       2.467139 -7.488149  19.800128                0.0
                2       2.653032  7.173953  15.740397                0.0
                3       4.620778 -5.738219  18.871566                0.0
       2054879  1       2.256291 -2.457408  15.740922                0.0
                2       2.163804  3.734823  12.596438                0.0

                        intensity_width_2  pixels_width_1  pixels_width_2  \
obs_id event_id tel_id
2923   2054766  1                0.000000             0.0        0.000000
                2                0.000000             0.0        0.000000
                3                0.000000             0.0        0.000000
       2054879  1                0.000000             0.0        0.000000
                2                0.022543             0.0        0.000962

                        n_pixels  n_islands  pointing_alt  pointing_az  \
obs_id event_id tel_id
2923   2054766  1             42          1      0.784340     1.508031
                2             61          1      0.784258     1.508029
                3             46          2      0.784235     1.508001
       2054879  1             10          1      0.784341     1.508032
                2             19          1      0.784258     1.508029

                           timestamp  time_diff  multiplicity  combo_type  \
obs_id event_id tel_id
2923   2054766  1       1.605743e+09   0.000020             3           3
                2       1.605743e+09   0.002003             3           3
                3       1.605743e+09   0.002003             3           3
       2054879  1       1.605743e+09   0.000029             3           3
                2       1.605743e+09   0.004651             3           3

                              alt  alt_uncert         az  az_uncert  \
obs_id event_id tel_id
2923   2054766  1       45.713880    0.185925  86.308094   0.185925
                2       45.713880    0.185925  86.308094   0.185925
                3       45.713880    0.185925  86.308094   0.185925
       2054879  1       44.084167    0.043847  86.058672   0.043847
                2       44.084167    0.043847  86.058672   0.043847

                           core_x     core_y      impact         h_max  \
obs_id event_id tel_id
2923   2054766  1       68.437147 -50.467934  117.100531  15205.132850
                2       68.437147 -50.467934   30.898989  15205.132850
                3       68.437147 -50.467934  101.768394  15205.132850
       2054879  1      -17.731262  75.937393    9.744626   3143.202157
                2      -17.731262  75.937393  110.243325   3143.202157

                        reco_energy  reco_energy_var  reco_disp  \
obs_id event_id tel_id
2923   2054766  1          1.160295         0.009623   0.818525
                2          0.966992         0.025346   0.597132
                3          1.013951         0.014466   0.709431
       2054879  1          0.349667         0.582411   0.734034
                2          0.219313         0.184645   1.042573

                        reco_disp_var   reco_alt    reco_az  disp_diff_sum  \
obs_id event_id tel_id
2923   2054766  1            0.033666  45.892510  86.571648       0.380246
                2            0.049796  45.873738  86.624261       0.380246
                3            0.023396  45.719292  86.656433       0.380246
       2054879  1            0.222867  44.145013  85.532415       2.757250
                2            0.287025  45.004017  86.638993       2.757250

                        disp_diff_mean  gammaness  gammaness_var  \
obs_id event_id tel_id
2923   2054766  1             0.126749   0.905000       0.085975
                2             0.126749   0.023333       0.022789
                3             0.126749   0.531095       0.249033
       2054879  1             0.919083   0.024167       0.023583
                2             0.919083   0.005000       0.004975

                            total_id      magic_id
obs_id event_id tel_id
2923   2054766  1       2923.2054766  5093174.2132
                2       2923.2054766  5093174.2132
                3       2923.2054766  5093174.2132
       2054879  1       2923.2054879  5093174.2134
                2       2923.2054879  5093174.2134

3T stereo with magic-cta-pipe (1597037 events):

                 combo_type  multiplicity     timestamp  pointing_alt  \
obs_id event_id
2923   2054766            3             3  1.605743e+09      0.784278
       2054879            3             3  1.605743e+09      0.784278
       2054932            3             3  1.605743e+09      0.784279
       2055078            3             3  1.605743e+09      0.784279
       2055274            3             3  1.605743e+09      0.784281

                 pointing_az  reco_energy   reco_alt    reco_az  gammaness  \
obs_id event_id
2923   2054766      1.508020     1.073560  45.808426  86.622282   0.229856
       2054879      1.508021     0.304828  44.365858  86.053244   0.005571
       2054932      1.508021     0.308370  43.797085  85.651368   0.575596
       2055078      1.508021     6.024152  44.133521  89.574563   0.010758
       2055274      1.508022     2.305442  43.991970  87.230756   0.217573

                 pointing_ra  pointing_dec    reco_ra   reco_dec  theta2_on  \
obs_id event_id
2923   2054766     83.966939     22.246320  83.020361  22.381911   0.457941
       2054879     83.966939     22.246321  84.636853  22.297141   0.944449
       2054932     83.966939     22.246322  85.319784  22.385995   2.577053
       2055078     83.966940     22.246323  83.945537  19.847722   4.774763
       2055274     83.966940     22.246324  84.715779  21.376468   1.417173

                 theta2_off      total_id
obs_id event_id
2923   2054766     1.416898  2923.2054766
       2054879     0.127986  2923.2054879
       2054932     0.890579  2923.2054932
       2055078     7.036542  2923.2055078
       2055274     1.362165  2923.2055274

LST with magic-cta-pipe (1597037 events):

                 combo_type  multiplicity     timestamp  pointing_alt  \
obs_id event_id
2923   2054766            3             3  1.605743e+09      0.784340
       2054879            3             3  1.605743e+09      0.784341
       2054932            3             3  1.605743e+09      0.784341
       2055078            3             3  1.605743e+09      0.784342
       2055274            3             3  1.605743e+09      0.784343

                 pointing_az  reco_energy   reco_alt    reco_az  gammaness  \
obs_id event_id
2923   2054766      1.508031     1.160295  45.892510  86.571648   0.905000
       2054879      1.508032     0.349667  44.145013  85.532415   0.024167
       2054932      1.508032     0.324521  43.923343  85.395259   0.259000
       2055078      1.508032     4.532147  44.364517  89.432862   0.005000
       2055274      1.508032     2.678414  43.922713  87.031510   0.000000

                 pointing_ra  pointing_dec    reco_ra   reco_dec  theta2_on  \
obs_id event_id
2923   2054766     83.963121     22.247061  82.946402  22.442243   0.588298
       2054879     83.963121     22.247064  84.993118  22.579120   1.903065
       2054932     83.963121     22.247065  85.254798  22.601497   2.596364
       2055078     83.963120     22.247069  83.754956  20.025401   3.964636
       2055274     83.963119     22.247074  84.837807  21.488128   1.527392

                 theta2_off      total_id
obs_id event_id
2923   2054766     1.560440  2923.2054766
       2054879     0.422463  2923.2054879
       2054932     0.796261  2923.2054932
       2055078     6.286444  2923.2055078
       2055274     1.237185  2923.2055274

MAGIC with magic-cta-pipe (1597037 events):

                 combo_type  multiplicity     timestamp  pointing_alt  \
obs_id event_id
2923   2054766            3             3  1.605743e+09      0.784247
       2054879            3             3  1.605743e+09      0.784247
       2054932            3             3  1.605743e+09      0.784247
       2055078            3             3  1.605743e+09      0.784248
       2055274            3             3  1.605743e+09      0.784249

                 pointing_az  reco_energy   reco_alt    reco_az  gammaness  \
obs_id event_id
2923   2054766      1.508015     0.996630  45.768662  86.646169   0.065903
       2054879      1.508015     0.296239  44.516516  86.414089   0.004001
       2054932      1.508015     0.303546  43.737947  85.770560   0.733074
       2055078      1.508016     9.079893  44.005319  89.652684   0.024489
       2055274      1.508016     2.165051  44.097895  87.538358   0.868484

                 pointing_ra  pointing_dec    reco_ra   reco_dec  theta2_on  \
obs_id event_id
2923   2054766     83.968847     22.245950  83.055307  22.353374   0.402099
       2054879     83.968848     22.245950  84.392417  22.102560   0.502953
       2054932     83.968848     22.245950  85.350054  22.285380   2.602299
       2055078     83.968850     22.245949  84.051062  19.749081   5.279012
       2055274     83.968851     22.245949  84.528308  21.204422   1.346666

                 theta2_off      total_id
obs_id event_id
2923   2054766     1.354486  2923.2054766
       2054879     0.147417  2923.2054879
       2054932     0.967444  2923.2054932
       2055078     7.505535  2923.2055078
       2055274     1.664926  2923.2055274

LST with lstchain (1597037 events):

,obs_id,event_id,intensity,x,y,r,time_gradient,intercept,alt_tel,az_tel,dragon_time,delta_t,reco_energy,reco_alt,reco_az,gammaness,reco_src_x,reco_src_y,reco_disp_norm,src_x,src_y,brightest_pixel,theta2_on,theta2_off,total_id
641447,2923,2054766,1539.117331,0.159153,-0.199730,0.255385,-7.488149,19.800128,0.784340,1.508031,1.605743e+09,0.000020,1.296785,0.802239,1.512487,0.849113,0.501298,0.086735,0.446235,0.109220,0.162819,199.895172,0.609734,1.662808,2923.2054766
641482,2923,2054879,222.561295,-0.455197,0.046522,0.457568,-2.457408,15.740922,0.784341,1.508032,1.605743e+09,0.000029,0.147946,0.769320,1.501430,0.050762,-0.420268,-0.132808,0.182700,0.109220,0.162821,43.858879,1.405720,0.373269,2923.2054879
641495,2923,2054932,493.258595,-0.599963,-0.179310,0.626185,10.961353,15.071617,0.784341,1.508032,1.605743e+09,0.000047,0.558524,0.766855,1.489840,0.201653,-0.487265,-0.366841,0.218789,0.109219,0.162821,54.278393,2.432366,0.705407,2923.2054932
641535,2923,2055078,5716.545122,-0.133117,0.249002,0.282351,12.083996,26.947308,0.784342,1.508032,1.605743e+09,0.000082,5.329910,0.775219,1.554315,0.006266,-0.240307,0.925506,0.684944,0.109219,0.162823,159.810211,2.690452,4.593233,2923.2055078
641595,2923,2055274,1982.416317,0.194891,0.360309,0.409640,14.399923,16.464350,0.784343,1.508032,1.605743e+09,0.000009,3.378833,0.769079,1.519712,0.006773,-0.426417,0.235006,0.633818,0.109217,0.162825,82.557724,1.116594,0.989577,2923.2055274

MAGIC with mars (1597037 events):

                  intensity_M1  intensity_M2  src_pos_M1_X  src_pos_M1_Y  \
obs_id  event_id
5093174 2132        682.093750    830.125000    -95.093643    -67.696632
        2134        185.757812     60.031250    -95.094864    -67.695946
        2136        210.335938    165.843750    -95.095299    -67.695694
        2140       1205.257812   1114.429688    -95.096870    -67.694801
        2141         89.109375    321.953125    -95.099022    -67.693573

                  src_pos_M2_X  src_pos_M2_Y     imp_par_1  imp_par_1_Az  \
obs_id  event_id
5093174 2132        -95.007812    -69.127335     -1.000000           NaN
        2134        -95.007668    -69.127419     -1.000000           NaN
        2136        -95.007614    -69.127449  10347.416992   -135.922577
        2140        -95.007416    -69.127563  33543.277344    -39.197220
        2141        -95.007156    -69.127724  37166.769531    -96.054169

                     imp_par_2  imp_par_2_Az   st_dirX   st_dirY  reco_energy  \
obs_id  event_id
5093174 2132         -1.000000           NaN       NaN       NaN    -0.001000
        2134         -1.000000           NaN       NaN       NaN    -0.001000
        2136       4091.868408    -99.179375  0.462942  1.156278     0.277724
        2140      37507.761719    -28.356291 -1.925715  0.639971     8.409363
        2141      33981.015625    -84.813004 -0.776421  0.846694     1.542577

                  gammaness   reco_dec    reco_ra      h_max   slope_1  \
obs_id  event_id
5093174 2132       0.081321        NaN        NaN      -1.00  0.431198
        2134       0.000000        NaN        NaN      -1.00  1.135765
        2136       0.411683  22.298716  84.311796  891360.75  0.714785
        2140       0.000000  20.215153  84.403027  968357.00 -0.567660
        2141       0.251661  21.232567  84.362278  979809.25  1.497397

                   slope_2  pointing_ra  pointing_dec     timestamp   delta_t  \
obs_id  event_id
5093174 2132      0.169814    84.401111     22.243889  1.737312e+09  0.002003
        2134     -1.296749    84.401111     22.243889  1.737705e+09  0.004651
        2136     -1.347897    84.401111     22.243889  1.737845e+09  0.002138
        2140     -0.512080    84.401111     22.243889  1.738355e+09  0.003429
        2141     -1.392613    84.401111     22.243889  1.739049e+09  0.008976

                      total_id  theta2_on  theta2_off
obs_id  event_id
5093174 2132      2923.2054766        NaN         NaN
        2134      2923.2054879        NaN         NaN
        2136      2923.2054932   0.476342    0.660850
        2140      2923.2055078   3.748868    5.614933
        2141      2923.2055274   1.068782    2.104545

In [10]:
# minutes of same wobble for the analysed runs
same_wobble = [36.7, 44.43, 55.2, 45.48, 94.92, 56.08, 107.4, 119.62, 81.94, 28.33, 127.86, 22.99, 84.26]

print(f'We have information from 3 telescopes from {len(same_wobble)} nights')
print(f'adding up to same wobble observations of {sum(same_wobble)/60:.2f}h')

print(f'The amount of total coincident 3T events we have are: {len(df_3T_cta)} events')

time_diffs = np.diff(df_3T_cta['timestamp'])
obs_time   = time_diffs[time_diffs < 1].sum() * u.s
obs_time   = obs_time.to('h')
print(f'\nTotal observation time: {obs_time:.1f}\n') 

n_events, n_C3, n_C2, n_C1, n_C0 = 7027323/3, 4791465/3, 906042/2, 962276/2, 367540/2
n_events = sum([n_C3, n_C2, n_C1, n_C0])
print(f'From a total non-stereo {int(n_events)} events:')
print(f'C0-Obtained  {int(n_C0)} events,\t{n_C0/n_events*100:.2f}%,\tM1 & M2')
print(f'C1-Obtained  {int(n_C1)} events,\t{n_C1/n_events*100:.2f}%,\tM1 & LST-1')
print(f'C2-Obtained  {int(n_C2)} events,\t{n_C2/n_events*100:.2f}%,\tM2 & LST-1')
print(f'C3-Obtained {int(n_C3)} events,\t{n_C3/n_events*100:.2f}%,\tM1 & M2 & LST-1')    
    
print(f'\nApplying cuts in gammaness:\n')
for g in [0.0, 0.1, 0.5, 0.7, 0.9, 0.99]:
    tmp = df_3T_cta.query(f'gammaness >= {g}', inplace=False)
    print(f'Gammaness > {g}:\t {len(tmp)} events\t ({len(tmp)/len(df_3T_cta)*100:.2f}%)')
    
    
print(f'\nFor MAGIC - MARS analysis:\t\t\t{len(df_magic_mars)} events are found')
print(f'For MAGIC - magic-cta-pipe analysis:\t\t{len(df_magic_cta)} events are found')
print(f'For LST - lstchain analysis:\t\t\t{len(df_lst_lst)} events are found')
print(f'For LST - magic-cta-pipe analysis:\t\t{len(df_lst_cta)} events are found')
print(f'For 3T stereo - magic-cta-pipe analysis:\t{len(df_3T_cta)} events are found')

We have information from 3 telescopes from 13 nights
adding up to same wobble observations of 15.09h
The amount of total coincident 3T events we have are: 1597037 events

Total observation time: 5.5 h

From a total non-stereo 2715084 events:
C0-Obtained  183770 events,	6.77%,	M1 & M2
C1-Obtained  481138 events,	17.72%,	M1 & LST-1
C2-Obtained  453021 events,	16.69%,	M2 & LST-1
C3-Obtained 1597155 events,	58.83%,	M1 & M2 & LST-1

Applying cuts in gammaness:

Gammaness > 0.0:	 1597037 events	 (100.00%)
Gammaness > 0.1:	 423279 events	 (26.50%)
Gammaness > 0.5:	 191349 events	 (11.98%)
Gammaness > 0.7:	 129575 events	 (8.11%)
Gammaness > 0.9:	 51218 events	 (3.21%)
Gammaness > 0.99:	 2326 events	 (0.15%)

For MAGIC - MARS analysis:			1597037 events are found
For MAGIC - magic-cta-pipe analysis:		1597037 events are found
For LST - lstchain analysis:			1597037 events are found
For LST - magic-cta-pipe analysis:		1597037 events are found
For 3T stereo - magic-cta-pipe analysis:	1597037 events are found

## Only reading dataframes code

In [11]:
# # --- main directory and filenames --- #
# dir_stereo_reco   = '/fefs/aswg/workspace/juan.jimenez/data/datasets/'
# name_stereo_3T    = 'stereo_data_3T'
# name_stereo_total = 'stereo_data_total'
# name_dl2_lst_2    = 'stereo_data_LST'
# name_stereo_magic = 'stereo_data_MAGIC'
# name_dl2_lst_1    = 'dl2_data_LST'
# name_dl2_magic    = 'dl2_data_MAGIC'

# # reading all data already produced
# df_total      = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_total}.h5'))
# df_3T_cta     = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_3T}.h5'))
# df_lst_cta    = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_lst_2}.h5'))
# df_magic_cta  = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_stereo_magic}.h5'))
# df_lst_lst    = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_lst_1}.h5'))
# df_magic_mars = pd.read_hdf(os.path.join(dir_stereo_reco, f'{name_dl2_magic}.h5'))